config/routes.rb
Rails.application.routes.draw do
  resource :index, only: :show
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]

  namespace :account do
    resource :profile, only: [:show, :update]
    resources :incomes, only: [:index, :create, :edit, :update, :destroy]
    resources :expenses, only: [:index]
    resources :stats, only: [:index]
    resources :random_expenses, only: [:index, :create, :edit, :update, :destroy]
    resources :recurrent_expenses, only: [:index, :create, :edit, :update, :destroy]
    resources :cards, only: [:index] do
      post :sync, on: :collection

      scope module: :cards do
        resources :transactions, only: [:index] do
          post :sync, on: :collection
        end
      end
    end

    root to: 'random_expenses#index'
  end

  root to: 'index#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :labels
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :user
  has_many :random_expenses
  has_many :recurrent_expenses

  monetize :limit_amount_cents
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  belongs_to :label
  belongs_to :day

  monetize :amount_cents
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user
  belongs_to :label, class_name: 'IncomeLabel'

  monetize :amount_cents
end

app/models/income_label.rb
class IncomeLabel < Label
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/random_expense.rb
class RandomExpense < Expense
end

app/models/random_expense_label.rb
class RandomExpenseLabel < Label
end

app/models/recurrent_expense.rb
class RecurrentExpense < Expense
end

app/models/recurrent_expense_label.rb
class RecurrentExpenseLabel < Label
end

app/models/user.rb
class User < ApplicationRecord
  ASSISTENT_MODES = %i(kirpich).freeze

  has_secure_password

  has_many :cards
  has_many :incomes
  has_many :random_expense_labels, class_name: 'RandomExpenseLabel'
  has_many :recurrent_expense_labels, class_name: 'RecurrentExpenseLabel'
  has_many :income_labels, class_name: 'IncomeLabel'
  has_many :random_expenses, class_name: 'RandomExpense'
  has_many :recurrent_expenses, class_name: 'RecurrentExpense'
  has_many :days

  def default_currency
    'RUB'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include ApplicationHelper
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
    if current_user.present?
      redirect_to account_root_path
    else
      redirect_to new_user_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    result = Users::Authenticate.call(
      email: session_params[:email],
      password: session_params[:password]
    )

    if result.success?
      sign_in result.user
      redirect_to account_root_path
    else
      flash[:error] = result.error
      render :new
    end
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_to account_root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/account/incomes_helper.rb
module Account::IncomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session[:user_id] = nil
  end

  def signed_in?
    !session[:user_id].nil?
  end

  def current_user
    return unless signed_in?

    User.find(session[:user_id])
  end

  def authenticate_user!
    redirect_to(root_path) unless signed_in?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/account.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    title= content_for?(:title) ? yield(:title) : t('wasted')
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'https://www.gstatic.com/charts/loader.js'
    = javascript_include_tag 'application'

  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type='button' data-toggle='collapse' data-target='.navbar-responsive-collapse'
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to t('wasted'), root_path, class: 'navbar-brand'
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li = link_to t('expenses'), account_expenses_path
              li = link_to t('incomes'), account_incomes_path
              li = link_to t('cards'), account_cards_path
              li = link_to t('stats'), account_stats_path
              li = link_to t('profile'), account_profile_path

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    title= content_for?(:title) ? yield(:title) : t('wasted')
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type='button' data-toggle='collapse' data-target='.navbar-responsive-collapse'
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to t('.wasted'), root_path, class: 'navbar-brand'
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to 'Link 1', '/path1'
              li= link_to 'Link 2', '/path2'
              li= link_to 'Link 3', '/path3'

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield